version: '2'

services:
  influxdb:
    image: influxdb:1.1-alpine
    ports:
      - "8083:8083"
      - "8086:8086"

  api:
    build: .
    links:
      - influxdb
    volumes:
      - .:/logsink_server
    ports:
      - "6789:6789"
    environment:
      #FLASK_APP: api.py
      FLASK_APP: logsink_server
      FLASK_DEBUG: 1
      ROOT_TOKEN: 'logsink-token'
      PYTHONPATH: /logsink_server
    command: flask run --host=0.0.0.0 --port 6789

  swagger-ui:
    image: swaggerapi/swagger-ui
    links:
      - api
    ports:
      - "6788:8080"
